server: 
  port: 9101
spring: 
  application:  
    name: clover-car #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-wz9i32b5zpqh03zo0ao.mysql.rds.aliyuncs.com:3306/clover_car?characterEncoding=UTF8&useSSL=false
    username: root
    password: 1994buyaozheyangA
  jpa: 
    database: MySQL
    show-sql: true
jwt:
  config:
    key: clover
    ttl: 3600000
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.0.0.47:6868/eureka
  instance:
    prefer-ip-address: true
ribbon:                      ##网络连接不好的时候需要配置
  ReadTimeout: 60000
  ConnectTimeout: 60000