server: 
  port: 9125
spring: 
  application:
    name: clover-upload #指定服务名
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 10MB
jwt:
  config:
    key: clover
    ttl: 3600000
eureka:
  client:
    serviceUrl:
      defaultZone: http://120.79.93.99:6868/eureka
  instance:
    prefer-ip-address: true
ribbon:                      ##网络连接不好的时候需要配置
  ReadTimeout: 60000
  ConnectTimeout: 60000

