server: 
  port: 9106
spring: 
  application:  
    name: clover-spitslot #指定服务名
  data:
    mongodb:
      host: 120.79.93.99
      database: spitslotdb
  redis:
    host: 120.79.93.99
jwt:
  config:
    key: clover
    ttl: 3600000
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.0.0.47:6868/eureka
  instance:
    prefer-ip-address: true
ribbon:                      ##网络连接不好的时候需要配置
  ReadTimeout: 60000
  ConnectTimeout: 60000